name: Automated Provisioning into AWS

#  Ser√° executada as atividade abaixo de forma manual
on:
  workflow_dispatch:

jobs:
  provisioning:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: cloud_infra/terraform

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.7.5"

    - name: Terraform initialization (e.g., download provider plugins)
      run: terraform init
    
    - name: Validation of Terraform script
      run: terraform validate

    - name: Generate Terraform execution plan
      run: terraform plan -out=tfplan